DROP TABLE IF EXISTS all_movies;
DROP TABLE IF EXISTS all_series;
DROP TABLE IF EXISTS all_seasons;
DROP TABLE IF EXISTS all_episodes;
DROP TABLE IF EXISTS movie_details;
DROP TABLE IF EXISTS votes;

DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS people CASCADE;
DROP TABLE IF EXISTS people_aliases CASCADE;
DROP TABLE IF EXISTS people_links CASCADE;
DROP TABLE IF EXISTS casts CASCADE;
DROP TABLE IF EXISTS job_names CASCADE;
DROP TABLE IF EXISTS jobs CASCADE;
--DROP TABLE IF EXISTS characters CASCADE;
DROP TABLE IF EXISTS movie_categories CASCADE;
DROP TABLE IF EXISTS movie_keywords CASCADE;
DROP TABLE IF EXISTS category_names CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS trailers CASCADE;
DROP TABLE IF EXISTS movie_links CASCADE;
DROP TABLE IF EXISTS image_ids CASCADE;
DROP TABLE IF EXISTS image_licenses CASCADE;
DROP TABLE IF EXISTS movie_aliases_iso CASCADE;
DROP TABLE IF EXISTS movie_languages CASCADE;
DROP TABLE IF EXISTS movie_countries CASCADE;
DROP TABLE IF EXISTS movie_references CASCADE;
DROP TABLE IF EXISTS movie_abstracts_de CASCADE;
DROP TABLE IF EXISTS movie_abstracts_en CASCADE;
DROP TABLE IF EXISTS movie_abstracts_fr CASCADE;
DROP TABLE IF EXISTS movie_abstracts_es CASCADE;

DROP TYPE IF EXISTS kind;

DROP TABLE IF EXISTS access_log;
