#!/bin/sh
set -eux

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER docker;
	CREATE DATABASE demo;
	GRANT ALL PRIVILEGES ON DATABASE demo TO docker;
  CREATE EXTENSION IF NOT EXISTS tsm_system_rows;
	\i omdb.sql
EOSQL
