#!/bin/sh

# https://www.omdb.org/content/Help:DataDownload
#
# Alle Textinformationen in omdb stehen sowohl unter der Creative
# Commons-Lizenz (Namensnennung 2.0 Deutschland) als auch unter der GNU-Lizenz
# für freie Dokumentation.

set -eu

BASE="https://www.omdb.org/data/"

FILES="
all_movies
all_series
all_seasons
all_episodes
all_movieseries

all_people
all_people_aliases
people_links

all_casts
job_names

movie_categories
movie_keywords
category_names
all_categories
trailers
movie_links

image_ids
image_licenses

all_movie_aliases_iso

all_votes
movie_languages
movie_countries
movie_details
movie_references
movie_abstracts_de
movie_abstracts_en
movie_abstracts_fr
movie_abstracts_es
movie_content_updates
"

# omitted: all_characters (not used in schema)
DATA_DIR="www.omdb.org/data"
rm -rf $DATA_DIR
mkdir -p $DATA_DIR


for f in $FILES; do

  if command -v wget > /dev/null 2>&1; then
    wget --no-verbose --mirror "$BASE$f.csv.bz2"
  else
    curl "$BASE$f.csv.bz2" -# --output $DATA_DIR/"$f.csv.bz2"
  fi
done
