#!/bin/sh

set -eu

FILES="
all_movies
all_series
all_seasons
all_episodes

all_people
all_people_aliases
people_links

all_casts
job_names
all_characters

movie_categories
movie_keywords
category_names
trailers
movie_links

image_ids
image_licenses

all_movie_aliases_iso

all_votes
movie_languages
movie_countries
movie_details
movie_references
movie_abstracts_de
movie_abstracts_en
"

for f in $FILES; do
  bzcat www.omdb.org/data/$f.csv.bz2 | ./import.pl $f
done

psql -c 'VACUUM' omdb
psql -c 'ANALYZE' omdb
