#!/bin/sh

set -eux

pg_virtualenv <<EOF
    set -eux
    export PGDATABASE=omdb
    createdb omdb
    psql -c 'create user postgres' || :
    pg_restore -l /usr/share/omdb-postgresql/omdb.dump > omdb.list
    grep -vw 'SCHEMA' omdb.list > omdb.filtered
    pg_restore -L omdb.filtered -d omdb -j4 /usr/share/omdb-postgresql/omdb.dump
    psql -c 'select * from people where id = 1' | grep 'George Lucas'
EOF
